# .github/workflows/sitemap-generator.yml

name: Generate Sitemap for jichangyun.com

on:
  push:
    branches:
      - main # 如果您的主分支是 master, 请修改此处

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          # 【关键修正】使用正确的参数名 base-url-path
          base-url-path: 'https://jichangyun.com'

      - name: Commit generated sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update sitemap.xml'
          file_pattern: 'sitemap.xml'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
