# .github/workflows/sitemap-generator.yml

name: Generate Sitemap

# 控制 Action 的触发时机
on:
  push:
    branches:
      - main  # 或者你的主分支名，可能是 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出你的仓库代码，Action 需要访问你的文件
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第二步：生成 Sitemap
      # 这个 Action 会扫描仓库中的 .html 文件并创建 sitemap.xml
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          # 【重要】将下面的 URL 替换成你自己的网站域名
          # 如果是项目主页，格式为 https://<username>.github.io/<repository>
          # 如果是用户主页或自定义域名，格式为 https://<your-domain.com>
          base-url: 'https://your-username.github.io/your-repository-name'

      # 第三步：自动提交生成的 sitemap.xml 文件
      # 如果 sitemap.xml 有变动，这个 Action 会自动将其提交到你的仓库
      - name: Commit Sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Auto-generate sitemap.xml'
          file_pattern: 'sitemap.xml' # 只提交 sitemap.xml 文件
