# .github/workflows/sitemap-generator.yml
# 这是一个完整且修正后的版本，用于自动为您的网站生成地图。

name: Generate Sitemap for jichangyun.com

# 触发条件：在每次向 main 分支推送代码时运行
on:
  push:
    branches:
      - main  # 注意：如果您的主分支是 master，请将此处的 main 修改为 master

# 授权：授予工作流向您的仓库写入文件的权限，这是解决 403 错误的关键。
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出（下载）您的仓库代码，以便工作流可以访问它
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 步骤 2: 运行 sitemap 生成器
      # 使用了正确的参数名 `base-url-path`
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: 'https://jichangyun.com'

      # 步骤 3: 自动提交生成的 sitemap.xml 文件
      - name: Commit generated sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Update sitemap.xml'
          file_pattern: 'sitemap.xml'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
